{%- set service_patterns = [cookiecutter.include_batch, cookiecutter.include_streaming] %}
{%- if service_patterns | select | list | length == 0 %}
services: {}
{%- else %}
services:
{%- if cookiecutter.include_batch %}
  airflow-standalone:
    image: apache/airflow:{{ cookiecutter.airflow_version }}
    command: standalone
    ports:
      - "8080:8080"
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      PYTHONPATH: /opt/airflow/project/src
      _PIP_ADDITIONAL_REQUIREMENTS: "pyarrow>=17.0{% if cookiecutter.include_lakehouse %} duckdb>=1.0{% endif %}"
    volumes:
      - ./src:/opt/airflow/project/src
      - ./src/{{ cookiecutter.project_slug }}/batch/dags:/opt/airflow/dags
{%- endif %}
{%- if cookiecutter.include_streaming %}
  kafka:
    image: confluentinc/cp-kafka:7.6.0
    ports:
      - "9092:9092"
    environment:
      CLUSTER_ID: MkU3OEVBNTcwNTJENDM2Qk
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
{%- endif %}
{%- endif %}
